#!/bin/bash

#do not change the lines numbers without changing them in the Create Eclipse_Mobots.sh script
#because it is used to actualise the line with arm-none-eabi

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export PATH=`/usr/libexec/java_home -v 1.8`/bin:$PATH

#below is the line changed by the script
export PATH=$dir/../Eclipse_Mobots/Tools/gcc-arm-none-eabi-5_4-2016q3/bin:$PATH

open $dir/../Eclipse_Mobots/eclipse.app --args -data $dir/../Eclipse_Mobots/Workspace